/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MedidorIMC;

//import javax.swing.JOptionPane;
import java.awt.Color;
import java.time.LocalDate;
import java.time.LocalDateTime;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author hegemn0
 */
public class MedidorIMC extends javax.swing.JFrame {

    /**
     * Creates new form MedidorIMC
     */
    public MedidorIMC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        txtNome = new javax.swing.JTextField();
        etqNome = new javax.swing.JLabel();
        etqDataN = new javax.swing.JLabel();
        etqPeso = new javax.swing.JLabel();
        txtSobrenome = new javax.swing.JTextField();
        etqSobrenome = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        etqSexo = new javax.swing.JLabel();
        cmbSexo = new javax.swing.JComboBox<>();
        etqTelefone = new javax.swing.JLabel();
        etqLog = new javax.swing.JLabel();
        btnCalcularIMC = new javax.swing.JButton();
        txtIMC = new javax.swing.JTextField();
        etqIMC = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        etqEndereco = new javax.swing.JLabel();
        etqAltura = new javax.swing.JLabel();
        etqTitulo = new javax.swing.JLabel();
        txtDataN = new javax.swing.JFormattedTextField();
        txtAltura = new javax.swing.JFormattedTextField();
        txtPeso = new javax.swing.JFormattedTextField();
        txtTelefone = new javax.swing.JFormattedTextField();
        spLog = new javax.swing.JScrollPane();
        txaLog = new javax.swing.JTextArea();
        btnGravar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        txtNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNome.setPreferredSize(new java.awt.Dimension(162, 30));

        etqNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        etqNome.setText("Nome:");

        etqDataN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        etqDataN.setText("Data de Nascimento:");

        etqPeso.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        etqPeso.setText("Peso(kg):");

        txtSobrenome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSobrenome.setPreferredSize(new java.awt.Dimension(162, 30));

        etqSobrenome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        etqSobrenome.setText("Sobrenome:");

        txtEndereco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtEndereco.setPreferredSize(new java.awt.Dimension(162, 30));

        etqSexo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        etqSexo.setText("Sexo:");

        cmbSexo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "F", "M", " " }));
        cmbSexo.setPreferredSize(new java.awt.Dimension(162, 30));
        cmbSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSexoActionPerformed(evt);
            }
        });

        etqTelefone.setText("Telefone:");

        etqLog.setText("Log:");

        btnCalcularIMC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCalcularIMC.setText("Calcular IMC");
        btnCalcularIMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularIMCActionPerformed(evt);
            }
        });

        txtIMC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtIMC.setPreferredSize(new java.awt.Dimension(162, 30));

        etqIMC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        etqIMC.setText("Índice de Massa Corporal:");

        btnLimpar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.setPreferredSize(new java.awt.Dimension(95, 30));
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setPreferredSize(new java.awt.Dimension(95, 30));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        etqEndereco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        etqEndereco.setText("Endereço:");

        etqAltura.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        etqAltura.setText("Altura(m):");

        etqTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        etqTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etqTitulo.setText("Medidor de Massa Corporal");

        txtDataN.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        txtDataN.setToolTipText("");
        txtDataN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDataN.setPreferredSize(new java.awt.Dimension(123, 30));

        txtAltura.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##"))));
        txtAltura.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtAltura.setPreferredSize(new java.awt.Dimension(123, 30));

        txtPeso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,#0"))));
        txtPeso.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPeso.setPreferredSize(new java.awt.Dimension(123, 30));

        try {
            MaskFormatter formatter = new MaskFormatter("(##)#####'-####");
            formatter.setOverwriteMode(true);
            formatter.setPlaceholder("0");
            formatter.setPlaceholderCharacter('#');
            formatter.setValidCharacters("0123456789");
            formatter.setValueContainsLiteralCharacters(true);
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(formatter));
            //jFormattedTextField4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####'-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone.setText("(##)#####-####");
        txtTelefone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTelefone.setPreferredSize(new java.awt.Dimension(162, 30));

        txaLog.setEditable(false);
        txaLog.setColumns(20);
        txaLog.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txaLog.setRows(5);
        spLog.setViewportView(txaLog);

        btnGravar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnGravar.setText("Gravar");
        btnGravar.setPreferredSize(new java.awt.Dimension(95, 30));
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnSair.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSair.setText("Sair");
        btnSair.setMaximumSize(new java.awt.Dimension(63, 23));
        btnSair.setMinimumSize(new java.awt.Dimension(63, 23));
        btnSair.setPreferredSize(new java.awt.Dimension(95, 30));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etqTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(etqNome)
                                        .addComponent(etqSobrenome)
                                        .addComponent(txtSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(etqTelefone)
                                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etqPeso)
                                    .addComponent(etqDataN)
                                    .addComponent(etqAltura)
                                    .addComponent(txtDataN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(etqEndereco))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etqSexo)
                                    .addComponent(cmbSexo, 0, 0, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCalcularIMC)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIMC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnGravar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(etqIMC))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(etqLog)
                                    .addGap(241, 241, 241))
                                .addComponent(spLog))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etqTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etqNome)
                    .addComponent(etqDataN)
                    .addComponent(etqLog))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDataN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etqSobrenome)
                            .addComponent(etqAltura))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etqPeso)
                            .addComponent(etqTelefone))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(etqSexo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(etqEndereco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addComponent(etqIMC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIMC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCalcularIMC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(spLog))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGravar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSexoActionPerformed

    private void btnCalcularIMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularIMCActionPerformed
        calcularIMC(Double.parseDouble(txtPeso.getText()), Double.parseDouble(txtAltura.getText()));
        
            if(txtIMC.getText().trim() != null || txtIMC.getText().trim() != "") {
                                
            double resutaldoIMC = Double.parseDouble(txtIMC.getText());
            
            if(resutaldoIMC < 18.5) {
                JOptionPane.showMessageDialog(this, "O índice de massa corporal deste paciente está abaixo de 18.5. Este paciente está abaixo do peso.");                                
            }
            if(resutaldoIMC > 18.5 && resutaldoIMC < 24.9) {
                JOptionPane.showMessageDialog(this, "O índice de massa corporal deste paciente é maior que 18.5 e menor que 24.9. Este paciente está saúdavel.");
                System.out.println("> 18.5 && < 24.9, peso normal");
            }
            if(resutaldoIMC > 25 && resutaldoIMC < 29.9) {
                JOptionPane.showMessageDialog(this, "O índice de massa corporal deste paciente é maior que 25 e menor que 29.9. Este paciente está acima do peso.");
                System.out.println("> 25 && < 29.9, acima do peso");   
            }
            if(resutaldoIMC > 30) {
                System.out.println("> 30, sobrepeso");   
                JOptionPane.showMessageDialog(this, "O índice de massa corporal deste paciente é igual ou maior que 30. Este paciente está obeso.");
            }
    }//GEN-LAST:event_btnCalcularIMCActionPerformed
    }
    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
            txaLog.setText("");
            txaLog.append("Nome: " + txtNome.getText());
            txaLog.append(" \nSobrenome: " + txtSobrenome.getText());
            txaLog.append(" \nNascimento: " + txtDataN.getText());
            txaLog.append(" \nAltura: " + txtAltura.getText());
            txaLog.append(" \nPeso: " + txtPeso.getText());
            txaLog.append(" \nIMC: " + txtIMC.getText());
            
            if(txtIMC.getText().trim() != null || txtIMC.getText().trim() != "") {
                                
            double resutaldoIMC = Double.parseDouble(txtIMC.getText());
            
            if(resutaldoIMC < 18.5) {
                txaLog.append(" \n< 18.5 des");
            }
            if(resutaldoIMC > 18.5 && resutaldoIMC < 24.9) {
                txaLog.append(" \n> 18.5 e < 24.9, peso normal");
            }
            if(resutaldoIMC > 25 && resutaldoIMC < 29.9) {
                txaLog.append(" \n> 25 e < 29.9, acima do peso");   
            }
            if(resutaldoIMC > 30) {
                txaLog.append(" \n> 30, sobrepeso");   
            }
            }      
            txaLog.append(" \nEndereco: " + txtEndereco.getText());
            txaLog.append(" \nSexo: " + cmbSexo.getSelectedItem());
            txaLog.append(" \nHorario: " + LocalDateTime.now());
            txaLog.append("\n\nConfirma? ");            
            

    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        txaLog.setText("");
        txaLog.append("\nGravado com sucesso!");
        txtNome.setText("");
        txtSobrenome.setText("");
        txtDataN.setText("");
        txtAltura.setText("");
        txtPeso.setText("");
        txtIMC.setText("");
        txtTelefone.setText("");
        txtEndereco.setText("");
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        txaLog.setText("");
        txtNome.setText("");
        txtSobrenome.setText("");
        txtDataN.setText("");
        txtAltura.setText("");
        txtPeso.setText("");
        txtIMC.setText("");
        txtTelefone.setText("");
        txtEndereco.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed
                
    private void dialogoIMC() {
        
    }
    
    private void calcularIMC(double peso, double altura) {                        
         txtIMC.setText(String.valueOf((peso / (altura * altura))));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedidorIMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedidorIMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedidorIMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedidorIMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MedidorIMC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularIMC;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbSexo;
    private javax.swing.JLabel etqAltura;
    private javax.swing.JLabel etqDataN;
    private javax.swing.JLabel etqEndereco;
    private javax.swing.JLabel etqIMC;
    private javax.swing.JLabel etqLog;
    private javax.swing.JLabel etqNome;
    private javax.swing.JLabel etqPeso;
    private javax.swing.JLabel etqSexo;
    private javax.swing.JLabel etqSobrenome;
    private javax.swing.JLabel etqTelefone;
    private javax.swing.JLabel etqTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JScrollPane spLog;
    private javax.swing.JTextArea txaLog;
    private javax.swing.JFormattedTextField txtAltura;
    private javax.swing.JFormattedTextField txtDataN;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtIMC;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtPeso;
    private javax.swing.JTextField txtSobrenome;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
